### ISSUE TITLE
BPM Should accept both packages and projects in the vendor/ directory

### ISSUE THREAD

**Issue by jtaby** [bpm/bpm#14]
Right now, you have to put projects in the vendor/ directory if you want to use them from source, and packages in the packages/ directory. I think that the distinction is an implementation detail and the user may not know whether something he's using is a package or a folder.

I talked to peterw and he said he can infer from the json whether it's a project or a directory, and we can combine both of them in the packages/ directory.

**Comment by ernesto-jimenez** [comment]
see https://github.com/bpm/bpm/pull/18
:)
