### ISSUE TITLE
`bpm preview` freezes

### ISSUE THREAD

**Issue by ebryn** [bpm/bpm#15]
I'm rather frequently having to restart the BPM preview server while running SC2 tests.

Ctrl-C doesn't even work. I have to Ctrl-Z and then `kill -9` it.

**Comment by wagenet** [comment]
This may be fixed on master. To try it out, create a Gemfile in the SC2 directory with the following

```
source 'http://rubygems.org'

gem "bpm", :git => "git://github.com/bpm/bpm.git"
```

and then run

```
bundle install
```

From there on out, use

```
bundle exec bpm
```

P.S. I know you know how to do this ebryn, this is for anyone else who runs across this.

**Comment by wagenet** [comment]
Hasn't been seen in a while. Assuming fixed.

**Comment by dudleyf** [comment]
I'm still seeing this on master (335543b) using Webrick on ruby-1.9.2-p290. The server hangs when trying to load resources under "/assets".
If I hack the preview command to run with the Thin handler instead of Webrick, the server runs without issues.
