### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by wagenet** [bpm/bpm#20]
Currently therubyracer doesn't work on Windows. We need to either fix therubyracer or remove the dependency.

**Comment by wagenet** [comment]
We've switched over to ExecJS, however Windows doesn't support symlinks, so we'll need to change that.

**Comment by jschilli** [comment]
running chcp 65001 in cmd.exe before running bpm preview/bpm rebuild seems to get past the error converting between IBM437 and UTF8

Unfortunately, a fatal error has occurred. Please report this error to the BPM issue tracker at https://github.com/bpm/bpm/i
ssues so that we can fix it. Thanks!
C:/Ruby192/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.beta.14/lib/bpm/pipeline/plugin_processor.rb:59:in `evaluate': incompatible ch
aracter encodings: IBM437 and UTF-8 (Encoding::CompatibilityError)
  (in C:/Users/Jeff/.bpm/gems/sproutcore-metal-2.0.beta.3/lib/accessors.js)
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/tilt-1.3.3/lib/tilt/template.rb:76:in`render'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/context.rb:175:in `block in evaluate'

```
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/context.rb:172:in `each'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/context.rb:172:in `evaluate'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:171:in `build_depend
```

ency_context_and_body'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:135:in `dependency_c
ontext'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:194:in`build_depend
encies_paths_and_assets'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:81:in `to_a'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:239:in`block in bui
ld_source'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/caching.rb:23:in `cache_hash'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:235:in`build_source
'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.beta.14/lib/bpm/pipeline.rb:154:in `find_asset'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/base.rb:111:in`[]'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:200:in `block in bui
ld_dependencies_paths_and_assets'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:194:in`each'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:194:in `build_depend
encies_paths_and_assets'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:81:in`to_a'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:239:in `block in bui
ld_source'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/caching.rb:23:in`cache_hash'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/sprockets-2.0.0.beta.15/lib/sprockets/bundled_asset.rb:235:in `build_source
'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.beta.14/lib/bpm/pipeline/generated_asset.rb:109:in`build_source'

```
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.beta.14/lib/bpm/pipeline.rb:154:in `find_asset'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.beta.14/lib/bpm/pipeline.rb:143:in `block in buildable_assets'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.beta.14/lib/bpm/pipeline.rb:143:in `map'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.beta.14/lib/bpm/pipeline.rb:143:in `buildable_assets'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.beta.14/lib/bpm/project.rb:300:in `build'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.beta.14/lib/bpm/cli/base.rb:129:in `rebuild'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/bpm-1.0.0.beta.14/bin/bpm:8:in `<top (required)>'
    from C:/Ruby192/bin/bpm:19:in `load'
    from C:/Ruby192/bin/bpm:19:in `<main>'
```

**Comment by wagenet** [comment]
Things should work in the windows branch. Pending additional verification. Also uses a branch of execjs so we'll need to get that approved or add monkey patches directly.

**Comment by wagenet** [comment]
All known Windows issues have been fixed. We can file new tickets if there are more.
