### ISSUE TITLE
bpm/qunit should support loading MyApp/bpm_lib.js for testing

### ISSUE THREAD

**Issue by jschilli** [bpm/bpm#25]
I've got a basic bpm setup for an application.  I'm building all of the dependencies into bpm_lib.js.

I have MyProject/bpm_lib.js which includes all of my app code.

The default spade-qunit html includes only bpm_lib.js so when you do

http://localhost:4020/assets/spade-qunit/index.html?package=MyProject, it attempts to `require(packageName)` which should load the MyProject/bpm_lib.js code and then load the tests for that package.

Alternative solutions might be to generate a test.html and project.json that have testing configured.

Thoughts?

**Comment by wagenet** [comment]
Due to our poor/nonexistent document I think you're a bit confused about how this should work `require('MyProject')` will attempt to load MyProject/lib/main.js it shouldn't try to load bpm_libs.js.

**Comment by jschilli** [comment]
Ok, got it.  The confusing thing is that bpm allows us to define the contents of the application in the project.json file.  require('MyProject') will only work if the directory structure matches a specific model

e.g.

```
lib/
   main.js (defines MyApp)
tests/
```

won't work even though it can be built with BPM

it would have to be

```
MyApp/
            main.js
tests
```

Correct?

**Comment by jschilli** [comment]
Peter,

I'll work up an example tomorrow to illustrate.  I still don't see how MyApp (the code) gets bootstrapped into the test if you've defined a project outside of the root bpm_libs.js

```
{
  "name": "MyApp",
  "bpm": "1.0.0",
  "bpm:build": {
  "bpm_libs.js": {
      "spade:format": "function",
          "directories": [
       ]
   },
   "bpm_styles.css": {
       "directories": [

      ]
   },
  "MyApp/bpm_libs.js": {
      "spade:format": "function",

       "directories": [
           "MyApp",
           "templates"
       ]
   },
   "MyApp/bpm_tests.js": {
     "directories": ["tests"],
     "modes": ["debug"]
   }

 ...
```

**Comment by wagenet** [comment]
The Spade config has some additional options.
require('MyProject') always loads lib/main.js but you can remap both the lib folder and main.js.
To remap directories for Spade, at the base level, use:

directories: {
    "lib": "./customlib"
}

If you want to remap main, use:

main: "./path/to/custom_main.js"

Hope that helps. Sorry for the lack of documentation.

-Peter

**Comment by jschilli** [comment]
No apologies necessary - just trying to keep moving forward.

I think my issue here was that I was defining MyApp as a separate build target in bpm (as seen above in the project.json snippet)

I've consolidated my app code into the bpm_lib.js target and now can run and test successfully.

Thanks again.
