### ISSUE TITLE
BPM is breaking handlebars format support in SproutCore 2.0

### ISSUE THREAD

**Issue by charlesjolley** [bpm/bpm#28]
Steps to reproduce:

```
bpm init hello_world
cd hello_world
bpm add sproutcore --pre  --version=2.0.0.beta.3
bpm add spade
touch lib/foo.handlebars
bpm rebuild
```

You will get a build error about `spade is not defined`.  I did some investigation and there are actually two bugs here, each of which would be worked around but together make this problem impossible to solve without changing BPM:
### Bug 1

When building the plugin asset for sproutcore-handlebars-format package, BPM is trying to wrap the format.js file in a spade.register() function event though sproutcore-handlebars-format does not depend on spade [but the app does].  It appears that the app's usage of spade is 'leaking' through to the plugin.  Plugins should build only with the dependencies of the plugin package itself, disregarding the dependencies of the app.
### Bug 2

In any event, the only reason this file is being built is because the sproutcore-handlebars-format package.json lists directories.lib == '.'.  Actually we don't want this package to have a lib AT ALL.  But if you remove this directive and then try to run `bpm pack` it will complain because there is no lib directory.  As far as I can tell, there is currently no way to build a package with no lib directory.  This should not be the case as some package - such as this one or maybe a CSS-only package - may not want to have a lib directory.

**Comment by charlesjolley** [comment]
Note that this prevents anyone from setting up an app with bpm to use sproutcore and handlebars right now.  See [this wiki page](https://github.com/bpm/bpm/wiki/Using-BPM-with-SproutCore-2.0) for an example of the workflow we want to support but currently cannot.

I can work around this issue temporarily by manually hacking the format package just after running `bpm add sproutcore` with:

```
mate .bpm/packages/sproutcore-handlebars-format/package.json
```

In there I change the `"lib": "."` line to be `"lib": "lib"` and then things will build.  Of course you can't just fix this in the package itself however because if you try to run `bpm pack` bpm will complain about the fact that `lib` does not actually exist.  Arg.

**Comment by wagenet** [comment]
I think there is some confusion about how the Handlebars wrapper should work. Right now the current expected usage IS with spade.

```
/*globals exports */
exports.compileFormat = function(code, context, filename) {
  return "return SC.Handlebars.compile("+JSON.stringify(code)+");";
};
```

You would then do:

```
SC.TEMPLATE[templateName] = spade.require('some_handlebars_template')
```

For this to work, the formatter has to supply a `return` since spade wraps in a closure.

However, it sounds like this isn't what you expect. Is your idea for the formatter to do something like this?

```
/*globals exports */
exports.compileFormat = function(code, context, filename) {
  var parts = filename.split('/');
  var name = JSON.stringify(parts[parts.length-1]);
  return "SC = SC || {};\n"+
         "SC.TEMPLATES = SC.TEMPLATES || {};\n"+
         "SC.TEMPLATES['"+name+"'] = SC.Handlebars.compile("+JSON.stringify(code)+");";
};
```

Anyway, this seems to me more of a confusion about behavior versus a bug.

However, we probably should allow packages without a lib directory. I will file that as a new ticket.

**Comment by charlesjolley** [comment]
The problem is that the plugin asset itself is generating spade - not the plugin output (that is fine).  To see what I mean open pipeline.rb and add log output around line 191 to log the plugin code before it is eval'd.  Then run the example above.  You will see the contents of format.js wrapped in a spade.register() call.

**Comment by wagenet** [comment]
I've traced this back to https://github.com/bpm/bpm/blob/master/lib/bpm/pipeline/package_pipeline.rb#L48-49

The sproutcore-handlebars-format package is fine on its own, since it doesn't require spade. The issue comes up when the format is re-provided by sproutcore-handlebars and sproutcore.

The Sprockets integration is so freaking confusing that it's taken me hours to figure out that much. It's going to be hard to figure out more without some assistance.

**Comment by salomons** [comment]
I installed BPM for the first time today and followed the guide on the wiki (https://github.com/bpm/bpm/wiki/Using-BPM-with-SproutCore-2.0) and I still got the spade is not defined error when trying to use handlebars..

**Comment by ernesto-jimenez** [comment]
Hi salomons,

I think peter fixed it in edge but hasn't released a gem update with the fix

On Fri, Sep 2, 2011 at 2:21 PM, salomons <
reply@reply.github.com>wrote:

> I installed BPM for the first time today and followed the guide on the wiki
> (https://github.com/bpm/bpm/wiki/Using-BPM-with-SproutCore-2.0) and I
> still got the spade is not defined error when trying to use handlebars..
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bpm/bpm/issues/28#issuecomment-1978876

## 

Ernesto Jiménez
http://twitter.com/ernesto_jimenez
http://www.linkedin.com/in/ernestojimenez
http://ernesto-jimenez.com

**Comment by salomons** [comment]
Hi Ernesto,

Thanks for your answer. How can I install edge? Or is it better to
wait for the gem maybe?

Thanks,
Hans

On 2 sep 2011, at 15:36, ernesto-jimenez
reply@reply.github.com
wrote:

> Hi salomons,
> 
> I think peter fixed it in edge but hasn't released a gem update with the fix
> 
> On Fri, Sep 2, 2011 at 2:21 PM, salomons <

**Comment by ernesto-jimenez** [comment]
I would suggest applying Charles's workaround until a new beta is released.

At least that's what I'm doing.

On 02/09/2011, at 17:01, salomons
reply@reply.github.com
wrote:

> Hi Ernesto,
> 
> Thanks for your answer. How can I install edge? Or is it better to
> wait for the gem maybe?
> 
> Thanks,
> Hans
> 
> On 2 sep 2011, at 15:36, ernesto-jimenez
> reply@reply.github.com
> wrote:
> 
> > Hi salomons,
> > 
> > I think peter fixed it in edge but hasn't released a gem update with the fix
> > 
> > On Fri, Sep 2, 2011 at 2:21 PM, salomons <

**Comment by salomons** [comment]
Ok, I'll try that.

Thanks,
Hans

On 2 sep 2011, at 18:18, ernesto-jimenez
reply@reply.github.com
wrote:

> I would suggest applying Charles's workaround until a new beta is released.
> 
> At least that's what I'm doing.
> 
> On 02/09/2011, at 17:01, salomons
> reply@reply.github.com
> wrote:
> 
> > Hi Ernesto,
> > 
> > Thanks for your answer. How can I install edge? Or is it better to
> > wait for the gem maybe?
> > 
> > Thanks,
> > Hans
> > 
> > On 2 sep 2011, at 15:36, ernesto-jimenez
> > reply@reply.github.com
> > wrote:
> > 
> > > Hi salomons,
> > > 
> > > I think peter fixed it in edge but hasn't released a gem update with the fix
> > > 
> > > On Fri, Sep 2, 2011 at 2:21 PM, salomons <

**Comment by DrewOJensen** [comment]
Any update on this? I'm also following the tut for SC2. I've got BPM 1.0rc1 + SC 2.0b3 and I'm getting the "ReferenceError: Can't find variable: spade" in safari web inspector.

**Comment by wagenet** [comment]
This sounds like a different error. If you think there is a bug, you can file a new ticket. Please try to share a minimal test case. At the very least I need to see a your project's JSON and also some information on where that error is being raised.

**Comment by devinus** [comment]
Following [this guide](https://github.com/bpm/bpm/wiki/Using-BPM-with-SproutCore-2.0), it seems the workaround is now:

```
$ mate ~/.bpm/gems/sproutcore-handlebars-format-2.0.beta.3.1/package.json
```

And change:

```
"lib": []
```

To:

```
"lib": "lib"
```

**Comment by wagenet** [comment]
@devinus, if you're using BPM RC1, sproutcore-handlebars-format beta 3.1 should NOT need to be modified. Can you say more why you think this is necessary?

**Comment by devinus** [comment]
Honestly I have no idea why it's necessary, but it does fix the issue. Confirmed for sure that I'm on BPM RC1 too.

**Comment by wagenet** [comment]
I'm pretty sure what you did will break non-spade apps. Most likely there's
a bug elsewhere. I'll give it a look though.

**Comment by wagenet** [comment]
@devinus, this should be fixed in master. I'll release RC2 soon.
