### ISSUE TITLE
bpm add sproutcore-datastore throws error

### ISSUE THREAD

**Issue by jschilli** [bpm/bpm#35]
Adding other packages seem to work fine.  

Bad sproutcore-datastore format?

Trace is here

schilling-mbpro-3:myapp jschilli $ bpm add sproutcore-datastore --pre
Fetching packages from remote...
~ Fetched spade (1.0.1) from remote
Unfortunately, a fatal error has occurred. Please report this error to the BPM issue tracker at https://github.com/bpm/bpm/issues so that we can fix it. Thanks!
/Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.2/lib/libgems/specification.rb:289:in `load': undefined class/module Syck::DefaultKey (ArgumentError)
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.2/lib/libgems/specification.rb:289:in`_load'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.2/lib/libgems/spec_fetcher.rb:133:in `load'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.2/lib/libgems/spec_fetcher.rb:133:in`fetch_spec'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.2/lib/libgems/spec_fetcher.rb:87:in `block in fetch_with_errors'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.2/lib/libgems/spec_fetcher.rb:86:in`map'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.2/lib/libgems/spec_fetcher.rb:86:in `fetch_with_errors'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/libgems_ext/dependency_installer.rb:129:in`find_gems_with_sources'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/libgems_ext/dependency_installer.rb:36:in `find_spec_by_name_and_version'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/libgems_ext/dependency_installer.rb:56:in`block in install'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.2/lib/libgems.rb:194:in `with_rubygems_compat'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/libgems_ext/dependency_installer.rb:54:in`install'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/remote.rb:83:in `block in install'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/libgems_ext/libgems.rb:43:in`with_silence'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/remote.rb:81:in `install'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/project.rb:620:in`core_fetch_dependency'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/project.rb:599:in `block in core_fetch_dependencies'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/project.rb:598:in`each'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/project.rb:598:in `core_fetch_dependencies'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/project.rb:216:in`add_dependencies'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/lib/bpm/cli/base.rb:93:in `add'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.beta.14/bin/bpm:8:in`<top (required)>'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in `load'
    from /Volumes/stendo/Users/jschilli/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in`<main>'

**Comment by wagenet** [comment]
Should be fixed in master.
