### ISSUE TITLE
bpm preview does not expose settings to plugins correctly

### ISSUE THREAD

**Issue by jschilli** [bpm/bpm#36]
Although bpm now calls build_source correctly, bpm does not pass/populate the settings hash correctly. (running master post #28 fix)

my project.json file has 

```
 "bpm:build": {

    "bpm_libs.js": {
        "spade:format": "function",      
         "directories": [
            "lib",
            "templates"
         ]
    },
```

the code under bpm rebuild is correctly 'spaded' - when run under bpm preview it is not.

I'm looking at this, but wanted to capture the issue.

**Comment by wagenet** [comment]
That works for me. I just tested. What is your dependencies hash like?

**Comment by jschilli** [comment]
It looks like this should be correct.

{
  "name": "Simplifi",
  "bpm": "1.0.0",
  "bpm:build": {

```
"bpm_libs.js": {
    "spade:format": "function",      
     "directories": [
        "lib",
        "templates"
     ]
}
```

  },
  "dependencies:development": {
    "spade-qunit": "~> 1.0.0",
    "qunit": ">= 0"
  },
  "dependencies": {
    "jquery": ">= 0",
    "spade": ">= 0",
    "sproutcore": ">= 0.pre",
    "sproutcore-datastore": ">= 0.pre"
  }

}

**Comment by wagenet** [comment]
Can you give me the detailed steps to reproduce?

**Comment by jschilli** [comment]
here's a gist illustrating the delta for 'my app'

https://gist.github.com/1173644

essentially, inspect element on the bpm preview version and look @ the bpm_libs.js files.  Goto the bottom and spade:format function could not have run

here's the git repo https://github.com/jschilli/bpm_test_app

it's a super basic app (we were using it before for testing)

**Comment by wagenet** [comment]
I think this is fixed. Had a bad responds_to? check.
