### ISSUE TITLE
Port to node.js

### ISSUE THREAD

**Issue by wagenet** [bpm/bpm#4]
When we first wrote BPM we decided to build off of RubyGems to help bootstrap. This saved us a lot of time and effort and was critical to getting BPM up and running. However, since the community is more interested in supporting JS code than Ruby code we're open to eventually porting the code to node.js. If anyone is interested in contributing to this effort, please respond here.

**Comment by ppcano** [comment]
+1

**Comment by wagenet** [comment]
Dead project
