### ISSUE TITLE
bpm rc1 on windows still challenged

### ISSUE THREAD

**Issue by jschilli** [bpm/bpm#45]
I removed all gems, ~/.bpm

git clone https://github.com/bpm/bpm.git
gem build bpm.gemspec
gem install bpm

bpm init mytest6

after failing repeatedly with 

C:/Users/Jeff/AppData/Local/Temp/execjs20110909-3360-18j97lt.js(6,5) : error JS1135: Variable 'result' has not been declared
C:/Users/Jeff/AppData/Local/Temp/execjs20110909-3360-18j97lt.js(11,15) : error JS1135: Variable 'JSON' has not been declared

I altered execjs to emit the javascript. 

Results in 

https://gist.github.com/1206225

**Comment by wagenet** [comment]
Is this the JSC issue we discussed on IRC or something new? If it's the JSC one, you can close it. It's fixed in master.
