### ISSUE TITLE
"ReferenceError: Can't find variable: spade"

### ISSUE THREAD

**Issue by DrewOJensen** [bpm/bpm#47]
I'm following the tut for SC2 (https://github.com/bpm/bpm/wiki/Using-BPM-with-SproutCore-2.0). I've got BPM 1.0rc1 + SC 2.0b3 and I'm getting the "ReferenceError: Can't find variable: spade" in safari web inspector.
I've notice in my json file:
{
  "name": "hello_world",
  "bpm": "1.0.0",
    "version": "0.0.1",
  "bpm:build": {
    "bpm_libs.js": {
      "files": [
        "lib", "templates"
      ],
      "minifier": "uglify-js"
    },
    "bpm_styles.css": {
      "files": [
        "css"
      ]
    }
  },
  "dependencies": {
    "sproutcore": ">= 0.pre",
    "spade": ">= 0"
  }
}

Under the bpm_libs.js file it has "files" rather than "directories" like in the tut. The "files" was there after a fresh project was created in BPM. Otherwise, all my other files are from a fresh project and ONLY the alterations/additions that the tut shows. From my testing, it is that when "templates" is added to the json file, that is when my main.js becomes unresponsive and I then get the error listed in the title.

**Comment by wagenet** [comment]
I think using the templates directory may be bad advice. I'll have to look into this more. For now, maybe try putting your handlebars files in lib/templates as lib/templates/my_template.handlebars, you can then require with `sc_require('templates/my_template')`.

**Comment by wagenet** [comment]
Should be fixed in master, will release RC2 soon.
