### ISSUE TITLE
`block in satisfied_by?': undefined method `call' for nil:NilClass 

### ISSUE THREAD

**Issue by aflatter** [bpm/bpm#53]
Hey guys,

Adding sproutcore to a fresh project does not work for me.

<pre><code>

bar:/tmp/ $ cd hello_world
bar:hello_world/ $ bpm add --pre sproutcore
You must specify at least one package
bar:hello_world/ $ bpm add sproutcore --pre
Fetching packages from remote...
Unfortunately, a fatal error has occurred. Please report this error to the BPM issue tracker at https://github.com/bpm/bpm/issues so that we can fix it. Thanks!
/home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `block in satisfied_by?': undefined method `call' for nil:NilClass (NoMethodError)
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `each'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `all?'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `satisfied_by?'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/source_index.rb:325:in `block in search'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/source_index.rb:323:in `select'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/source_index.rb:323:in `search'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/source_index.rb:280:in `find_name'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/installer.rb:214:in `installation_satisfies_dependency?'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/installer.rb:204:in `ensure_dependency'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/installer.rb:418:in `block in ensure_dependencies_met'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/installer.rb:417:in `each'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/installer.rb:417:in `ensure_dependencies_met'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems/installer.rb:136:in `install'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/libgems_ext/dependency_installer.rb:96:in `block (2 levels) in install'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/libgems_ext/dependency_installer.rb:66:in `each'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/libgems_ext/dependency_installer.rb:66:in `block in install'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/libgems-0.1.3/lib/libgems.rb:221:in `with_rubygems_compat'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/libgems_ext/dependency_installer.rb:54:in `install'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/remote.rb:83:in `block in install'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/libgems_ext/libgems.rb:43:in `with_silence'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/remote.rb:81:in `install'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/project.rb:621:in `core_fetch_dependency'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/project.rb:600:in `block in core_fetch_dependencies'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/project.rb:599:in `each'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/project.rb:599:in `core_fetch_dependencies'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/project.rb:217:in `add_dependencies'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/cli/base.rb:105:in `add'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/lib/bpm/cli/base.rb:25:in `start'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/gems/bpm-1.0.0.rc.2/bin/bpm:8:in `<top (required)>'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/bin/bpm:19:in `load'
    from /home/foo/.rvm/gems/ruby-1.9.2-p136/bin/bpm:19:in `<main>'

</code></pre>

**Comment by aflatter** [comment]
Related to the syck drama. Updated my ruby version from 1.9.2p136 to 1.9.2-p290 and now everything works as expected. Closing this. :)

**Comment by chrisconley** [comment]
I just upgraded to 1.9.2-p290 but still getting this error.

**Comment by aflatter** [comment]
Probably related to #37.

**Comment by tothda** [comment]
I struggled with this issue today. I think it reappeared in libgems 0.1.3. Downgrading to 0.1.2 solves the problem for me.

See the log here: http://pastie.org/2664931

**Comment by oldfartdeveloper** [comment]
I'm still struggling with this issue.

Ruby 1.9.2-p290 under Mac Lion with BPM version 1.0.0.

I followed exactly the steps in the wiki: https://github.com/bpm/bpm/wiki/Using-BPM-with-SproutCore-2.0.  When I get to the step 'bpm add sproutcore --pre', I get the above error.
