### ISSUE TITLE
add sproutcore --pre fails

### ISSUE THREAD

**Issue by salomons** [bpm/bpm#56]
When trying to add sproutcore --pre to a project I get:

Unfortunately, a fatal error has occurred. Please report this error to the BPM issue tracker at https://github.com/bpm/bpm/issues so that we can fix it. Thanks!
/usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `block in satisfied_by?': undefined method`call' for nil:NilClass (NoMethodError)
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `each'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in`all?'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `satisfied_by?'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/source_index.rb:325:in`block in search'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/source_index.rb:323:in `select'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/source_index.rb:323:in`search'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/source_index.rb:280:in `find_name'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:214:in`installation_satisfies_dependency?'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:204:in `ensure_dependency'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:418:in`block in ensure_dependencies_met'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:417:in `each'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:417:in`ensure_dependencies_met'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems/installer.rb:136:in `install'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/libgems_ext/dependency_installer.rb:96:in`block (2 levels) in install'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/libgems_ext/dependency_installer.rb:66:in `each'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/libgems_ext/dependency_installer.rb:66:in`block in install'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/libgems-0.1.3/lib/libgems.rb:221:in `with_rubygems_compat'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/libgems_ext/dependency_installer.rb:54:in`install'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/remote.rb:83:in `block in install'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/libgems_ext/libgems.rb:43:in`with_silence'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/remote.rb:81:in `install'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/project.rb:621:in`core_fetch_dependency'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/project.rb:600:in `block in core_fetch_dependencies'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/project.rb:599:in`each'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/project.rb:599:in `core_fetch_dependencies'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/project.rb:217:in`add_dependencies'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/cli/base.rb:105:in `add'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/lib/bpm/cli/base.rb:25:in`start'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/gems/bpm-1.0.0.rc.3/bin/bpm:8:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/bin/bpm:19:in`load'
    from /usr/local/rvm/gems/ruby-1.9.2-p180/bin/bpm:19:in `<main>'

I have tried with both ruby p180 and p290. However using without --pre seems to work..

**Comment by wagenet** [comment]
@salomons make sure you are using the most recent version of both rvm and of rubygems. I just talked to someone who had the same issue and upgrading both of these fixed it. If this doesn't solve it for you, let me know.

**Comment by salomons** [comment]
Thanks, now it works! If someone else has this problem; it didn't work by only upgrading rvm and ruby. I had files of old versions of bpm still around even do I had gem removed them. Removing rvm and installing it again is not a very advanced solution, but that was what I did and than it worked. Thanks again. However I still can't get statecharts to work with bpm. Is it working for you?

**Comment by wagenet** [comment]
What sort of issues are you having with statcharts?

**Comment by salomons** [comment]
I can't use require('sproutcore-statechart'). When I do I get syntax error:
__evalFunc = function(a,b,c,d,e,f){var...efined)};return c.statePlugin=YES,c}}
in bpm_lib.js. I have absolutely no clue what is going wrong. I follow the guide at https://github.com/bpm/bpm/wiki/Using-BPM-with-SproutCore-2.0 to set things up. 

// core.js
require('sproutcore');
App = SC.Application.create();
alert('core');

// main.js
require('./core');
require('sproutcore-statechart');
alert('main')

When I comment out require('sproutcore-statechart') it works so something goes wrong. I use sproutcore-statechart 2.0.beta3 by adding it with bpm add sproutcore-statechart -v 2.0.beta.3 --pre. Tried to add it with bpm add sproutcore-statechart, but I get the same error.

**Comment by wagenet** [comment]
Works fine for me. Can you give me exact steps to reproduce and create a new ticket?

**Comment by salomons** [comment]
Thanks for taking a look at it! Updated my ticket at https://github.com/sproutcore/sproutcore-statechart/issues/1.
