### ISSUE TITLE
bpm add sproutcore --pre: fatal error has occurred

### ISSUE THREAD

**Issue by zuudo** [bpm/bpm#57]
/Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `block in satisfied_by?': undefined method`call' for nil:NilClass (NoMethodError)
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `each'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in`all?'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/requirement.rb:145:in `satisfied_by?'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/source_index.rb:325:in`block in search'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/source_index.rb:323:in `select'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/source_index.rb:323:in`search'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/source_index.rb:280:in `find_name'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:214:in`installation_satisfies_dependency?'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:204:in `ensure_dependency'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:418:in`block in ensure_dependencies_met'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:417:in `each'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:417:in`ensure_dependencies_met'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems/installer.rb:136:in `install'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/libgems_ext/dependency_installer.rb:96:in`block (2 levels) in install'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/libgems_ext/dependency_installer.rb:66:in `each'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/libgems_ext/dependency_installer.rb:66:in`block in install'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/libgems-0.1.3/lib/libgems.rb:221:in `with_rubygems_compat'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/libgems_ext/dependency_installer.rb:54:in`install'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/remote.rb:83:in `block in install'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/libgems_ext/libgems.rb:43:in`with_silence'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/remote.rb:81:in `install'
        from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/project.rb:621:in`core_fetch_dependency'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/project.rb:600:in `block in core_fetch_dependencies'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/project.rb:599:in`each'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/project.rb:599:in `core_fetch_dependencies'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/project.rb:217:in`add_dependencies'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/cli/base.rb:105:in `add'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/lib/bpm/cli/base.rb:25:in`start'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0.rc.3/bin/bpm:8:in `<top (required)>'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in`load'
    from /Users/frank/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in `<main>'

**Comment by zuudo** [comment]
I'm using bpm (v1.0.0.rc.3) on Lion

**Comment by wagenet** [comment]
You're on the latest Ruby, but make sure you're on the latest RVM and RubyGems. Everyone else who has had this issue has resolved it with this.

**Comment by zuudo** [comment]
Sorry, I'm still getting the same error. I've upgrade RVM to v 1.8.3 and successfully installed rubygems-update-1.8.10 and I am still getting the same error. Below is a list of my gems.

**\* LOCAL GEMS ***

bpm (1.0.0.rc.3, 0.1.4)
bundler (1.0.18, 1.0.15)
childlabor (0.0.3)
daemons (1.1.4)
eventmachine (1.0.0.beta.4, 0.12.10)
execjs (1.2.8, 1.2.7, 1.2.6, 1.2.0)
gemcutter (0.7.0, 0.6.1)
highline (1.6.2)
hike (1.2.1, 1.2.0)
json_pure (1.6.1, 1.4.6)
libgems (0.1.3, 0.0.5)
libv8 (3.3.10.2)
multi_json (1.0.3)
rack (1.3.3, 1.2.3)
rake (0.9.2)
rubygems-update (1.8.10)
spade (0.1.1.1)
sprockets (2.0.0)
therubyracer (0.9.4, 0.9.3beta1)
thin (1.2.11)
thor (0.14.6)
tilt (1.3.3, 1.3.2)
uglifier (1.0.3, 1.0.0)

It seems to work when I don't add the --pre flag

bpm add sproutcore
Fetching packages from remote...
Added package 'sproutcore' (2.0.beta.3)
Added package 'sproutcore-runtime' (2.0.beta.3)
Added package 'sproutcore-views' (2.0.beta.3)
Added package 'sproutcore-handlebars' (2.0.beta.3)
Added package 'sproutcore-handlebars-format' (2.0.beta.3)
Added package 'sproutcore-metal' (2.0.beta.3)
Added package 'jquery' (1.6.2)
Added package 'handlebars' (1.0.0.beta.3)
Building static assets...
~ Using fetched package 'sproutcore' (2.0.beta.3)
~ Using fetched package 'uglify-js' (1.0.7)
~ Using fetched package 'spade' (1.0.1)
~ Using fetched package 'sproutcore-runtime' (2.0.beta.3)
~ Using fetched package 'sproutcore-views' (2.0.beta.3)
~ Using fetched package 'sproutcore-handlebars' (2.0.beta.3)
~ Using fetched package 'sproutcore-handlebars-format' (2.0.beta.3)
~ Using fetched package 'sproutcore-metal' (2.0.beta.3)
~ Using fetched package 'jquery' (1.6.2)
~ Using fetched package 'handlebars' (1.0.0.beta.3)
~ Building bpm_libs.js... (gzipped size: 67 Kb)
~ Building bpm_styles.css... (gzipped size: 254 bytes)

[WARN] 3859 deprecation warnings were hidden. Run with --verbose to see them.

Any help would be appreciated.

Thanks
Frank

**Comment by wagenet** [comment]
Try removing your ~/.bpm directory. There may be some bad data cached.

**Comment by chrisconley** [comment]
I'm still getting the same error with `rvm 1.8.4`, `ruby-1.9.2-p290`, and `rubygems 1.8.10` even after removing my `~/.bpm` directory.

**Comment by wagenet** [comment]
Does the problem exist with a brand new app?

**Comment by chrisconley** [comment]
Yeah, it still happened with a newly created bpm app.

I just completely reinstalled rvm as another user on another issue suggested and that fixed the issue. Phew!

**Comment by wagenet** [comment]
Seems like something is jacked with RVM :/ But glad you solved it.
