### ISSUE TITLE
`bpm add _____ --package` Failing

### ISSUE THREAD

**Issue by ColinCampbell** [bpm/bpm#67]
```
± bpm add jquery --package
You do not appear to be inside of a bpm project
```

On the wiki for creating a package, this command is listed. I was using the package_template from the repo.

**Comment by wagenet** [comment]
Are you on RC4?

**Comment by wagenet** [comment]
![Upgrade!](http://images.memegenerator.net/instances/400x/10224571.jpg)

**Comment by ColinCampbell** [comment]
![y u no](http://images.memegenerator.net/instances/400x/10224616.jpg)

**Comment by wagenet** [comment]
Fine, you can use RC3, without `--package`.

**Comment by ColinCampbell** [comment]
<3

**Comment by devinus** [comment]
This exchange just made me ROFL.
