### ISSUE TITLE
Missing documentation on how to package images

### ISSUE THREAD

**Issue by jeroenvandijk** [bpm/bpm#71]
From the Readme: _(bpm) Handles non-JS assets such as CSS and images._

I have an app that has js, css and images assets. How should I define where images can be found or how they should be packaged? I've looked in the BPM code, but didn't find any hints to how I should tackle this.

**Comment by wagenet** [comment]
I think for images it's probably best to put them in the assets directory. We may want to change that description since currently BPM does nothing special with images. At some point we may add in support for spriting or the like.
