### ISSUE TITLE
https://getbpm.org isn't reachable anymore

### ISSUE THREAD

**Issue by stefri** [bpm/bpm#72]
Just updated some package dependencies and noticed that bpm can't reach https://getbpm.org anymore. It throws the following error message for each package:

```
Fetching packages from remote...
ERROR:  https://getbpm.org/ does not appear to be a repository
...
```

Since the site is now running under https://www.getbpm.org it seems like a configuration error.

**Comment by stefri** [comment]
To overcome this issue I manually changed my bpm gem to use https://www.getbpm.org as url. I had to change two lines in 

lib/bpm/libgems_ext/libgems.rb:    

```
Line 5: %w[https://getbpm.org/]
Line 9: @host ||= "https://getbpm.org"
```

to get bpm working again.

**Comment by stefri** [comment]
Sorry didn't close this on purpose ...

**Comment by wagenet** [comment]
BPM is now on 1.0.0 release. Run `gem install bpm` to get this release which fixes the problem. If you're curious, we switched to proper SSL which doesn't support the root domain in our setup.
