### ISSUE TITLE
invalid byte sequence in UTF-8 (ArgumentError) causes by bpm init

### ISSUE THREAD

**Issue by everplays** [bpm/bpm#84]
here's full trace: http://pastebin.com/b7uKuXSZ

I'm using:
    bpm: 1.0.0 rc4
    ruby: 1.9.2
    OS: GNU/Linux - Fedora

**Comment by wagenet** [comment]
Please use BPM 1.0.0 final. RC4 is outdated. If you still have issues, let me know.

**Comment by everplays** [comment]
yes, same issue with 1.0.0

http://pastebin.com/HmiuZfhX

**Comment by wagenet** [comment]
Can you give me the output of: `ruby -e "require 'execjs'; puts ExecJS.runtime"`

**Comment by everplays** [comment]
yes, here's output:

$ ruby -e "require 'execjs'; puts ExecJS.runtime"
`#<ExecJS::ExternalRuntime:0x0000000159c238>`
$

**Comment by wagenet** [comment]
Sorry, should have asked you to run: `ruby -e "require 'execjs'; puts ExecJS.runtime.inspect"`

**Comment by everplays** [comment]
np

$ ruby -e "require 'execjs'; puts ExecJS.runtime.inspect"
`#<ExecJS::ExternalRuntime:0x000000021d9d20 @name="SpiderMonkey", @command="js", @runner_path="/home/behrooz/.rvm/gems/ruby-1.9.2-p180/gems/execjs-1.2.9/lib/execjs/support/spidermonkey_runner.js", @test_args=nil, @test_match=nil, @encoding=nil, @binary="/usr/bin/js">`
$
