### ISSUE TITLE
Crash bpm rebuild/preview using ubuntu 11.04

### ISSUE THREAD

**Issue by vdveer** [bpm/bpm#90]
Running bpm preview and rebuild causes the following crash. Using Ubuntu 11.04, ruby 1.9.2, bpm 1.0.0.

Any help is appreciated!

gebruiker@generic:~/workspace-somapp/somapp$ bpm rebuild
Building static assets...
~ Using fetched package 'sproutcore' (2.0.beta.3.1)
~ Using fetched package 'spade' (1.0.2)
~ Using local package 'sproutcore-touch' (2.0.beta.1)
~ Using fetched package 'sproutcore-statechart' (2.0.beta.4)
~ Using fetched package 'iscroll' (4.1.9)
~ Using fetched package 'jquery-easing' (1.3.0)
~ Using fetched package 'sproutcore-datetime' (2.0.beta.3)
~ Using fetched package 'sproutcore-localstorage' (2.0.beta.6)
~ Using fetched package 'sproutcore-routing' (2.0.beta.8)
~ Using fetched package 'spin' (1.2.2)
~ Using fetched package 'spade-qunit' (1.0.1)
~ Using fetched package 'jasmine' (1.1.0.build4)
~ Using fetched package 'spade-jasmine' (1.1.0.build2)
~ Using fetched package 'uglify-js' (1.0.7)
~ Using fetched package 'sproutcore-runtime' (2.0.beta.3)
~ Using fetched package 'sproutcore-views' (2.0.beta.3)
~ Using fetched package 'sproutcore-handlebars' (2.0.beta.3)
~ Using fetched package 'sproutcore-handlebars-format' (2.0.beta.3.1)
~ Using fetched package 'jquery' (1.6.2)
~ Using fetched package 'TransformJS' (1.0.beta.2)
~ Using fetched package 'sproutcore-utils' (2.0.beta.3)
~ Using fetched package 'qunit' (1.0.1)
~ Using fetched package 'sproutcore-metal' (2.0.beta.3)
~ Using fetched package 'handlebars' (1.0.0.beta.3)
Unfortunately, a fatal error has occurred. Please report this error to the BPM issue tracker at https://github.com/bpm/bpm/issues so that we can fix it. Thanks!
/home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/execjs_ext.rb:23:in `exec_runtime': js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1173: missing name after . operator (ExecJS::RuntimeError)
js:   pkg = callingId ? spade.package(callingId) : null;
js: .................................^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1223: missing name after . operator
js:   pkg = callingId ? spade.package(callingId) : null;
js: .................................^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1262: missing name after . operator
js:   pkg = callingId ? spade.package(callingId) : null;
js: .................................^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1294: missing name after . operator
js:   pkg = callingId ? spade.package(callingId) : null;
js: .................................^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1297: missing name after . operator
js:   pkg = spade.package(id);
js: .....................^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1301: missing name after . operator
js:     pkg = spade.package(id);
js: .......................^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1333: missing name after . operator
js:   var pkg     = spade.package(id),
js: .............................^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1334: syntax error
js:       sandbox = this,
js: ...............^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1968: missing name after . operator
js: Tp.package = function(id) {
js: ..........^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1969: syntax error
js:   id = packageIdFor(normalize(id))+'/~package';
js: ......^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 1972: missing ) in parenthetical
js: };
js: .^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 2105: invalid return
js: return eval("(BPM_PLUGIN.compileTransport(DATA, CTX, '/home/gebruiker/.bpm/gems/uglify-js-1.0.7/lib/parse-js.js'))")
js: ......^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 2106: syntax error
js: }, function(program) {
js: ^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 2587: missing ; before statement
js: }(this));
js: .......^
js: "/tmp/execjs20111128-4547-1gupv4u.js", line 2604: syntax error
js: });
js: ^

  (in /home/gebruiker/.bpm/gems/sproutcore-metal-2.0.beta.3/lib/accessors.js)
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/execjs-1.2.9/lib/execjs/external_runtime.rb:27:in `block in exec'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/execjs-1.2.9/lib/execjs/external_runtime.rb:40:in`compile_to_tempfile'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/execjs-1.2.9/lib/execjs/external_runtime.rb:26:in `exec'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/execjs-1.2.9/lib/execjs/external_runtime.rb:18:in`eval'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline/plugin_processor.rb:61:in `evaluate'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/tilt-1.3.3/lib/tilt/template.rb:76:in`render'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/context.rb:175:in `block in evaluate'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/context.rb:172:in`each'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/context.rb:172:in `evaluate'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:171:in`build_dependency_context_and_body'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:135:in `dependency_context'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:194:in`build_dependencies_paths_and_assets'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:81:in `to_a'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:239:in`block in build_source'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/caching.rb:27:in `cache_hash'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:235:in`build_source'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline.rb:153:in `find_asset'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/base.rb:110:in`[]'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:200:in `block in build_dependencies_paths_and_assets'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:194:in`each'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:194:in `build_dependencies_paths_and_assets'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:81:in`to_a'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:239:in `block in build_source'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/caching.rb:27:in`cache_hash'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:235:in `build_source'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline/generated_asset.rb:108:in`build_source'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:93:in `to_s'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline.rb:196:in`build_plugin_js'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline.rb:146:in `plugin_js_for'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline/generated_asset.rb:44:in`minify_as_js'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline/plugin_context.rb:15:in `minify_as_js'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline/plugin_processor.rb:50:in`evaluate'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/context.rb:175:in`block in evaluate'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/context.rb:172:in `each'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/context.rb:172:in`evaluate'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:171:in `build_dependency_context_and_body'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:135:in`dependency_context'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:194:in `build_dependencies_paths_and_assets'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:81:in`to_a'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:239:in `block in build_source'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/caching.rb:27:in`cache_hash'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:235:in `build_source'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline.rb:153:in`find_asset'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/base.rb:110:in `[]'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:200:in`block in build_dependencies_paths_and_assets'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:194:in `each'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:194:in`build_dependencies_paths_and_assets'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:81:in `to_a'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:239:in`block in build_source'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/caching.rb:27:in `cache_hash'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.3/lib/sprockets/bundled_asset.rb:235:in`build_source'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline/generated_asset.rb:108:in `build_source'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline.rb:153:in`find_asset'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline.rb:142:in `block in buildable_assets'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline.rb:142:in`map'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/pipeline.rb:142:in `buildable_assets'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/project.rb:297:in`build'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/cli/base.rb:236:in `rebuild'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/lib/bpm/cli/base.rb:59:in`start'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/gems/bpm-1.0.0/bin/bpm:8:in `<top (required)>'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in`load'
    from /home/gebruiker/.rvm/gems/ruby-1.9.2-p290/bin/bpm:19:in `<main>'

**Comment by vdveer** [comment]
dependencies missing, try:

gem install execjs
gem install therubyracer

source: ralfschimmel

**Comment by ralfschimmel** [comment]
Nice ;-)

The above error message is less clear than the one produced when using 1.9.3 though.
